### ISSUE TITLE
Link to awesome ecs

### ISSUE THREAD

**Issue by dzmitry-lahoda** [0xFA11/MultiplayerNetworkingResources#22]
I guess it is frequent to have ECS with good networking. May be link to https://github.com/jslee02/awesome-entity-component-system  in the end under related catalog in the end could be relevant.

**Comment by 0xFA11** [comment]
Hey Dzmitry,

Sorry for my late response, I was overwhelmed with some other work at office.

I think ECS and DOD stuff are really great, however I also believe we should keep this list as "network things" instead of "network AND RELATED things".
So, I kind of want to not include other areas/categories directly.

Do you think that makes sense and fair?

Thank you.
