### ISSUE TITLE
gameserverarchitecture.com seems to be down

### ISSUE THREAD

**Issue by ondrowan** [0xFA11/MultiplayerNetworkingResources#28]
It loads just blank page for me.

**Comment by 0xFA11** [comment]
Oh yeah, it looks like website is down now :(

I will update the entry with Archive.org backup soon.
Good spot, thanks for letting me know — cheers! :)

**Comment by 0xFA11** [comment]
Yup, backup link went in with c7b0e69

**Comment by ertenmehmet** [comment]
wow such that was a misery to see such a rich resource down, but I am quite glad to see it is kept in archive.org. But that would be better to ask @matsaleh13 to make it happen again!! Waiting to see your support on this :))

**Comment by 0xFA11** [comment]
Hey @ertenmehmet,

Yeah, it's sad to see website going down and I'm not sure how much of the content is archived :(
However I'm not sure how could I convince @matsaleh13 to put it back online again.

Do you want me to reach out to him over email or LinkedIn?
(I didn't quite understand what you want me to do about this, sorry)

Please let me know — thanks!

**Comment by matsaleh13** [comment]
Hey Guys,

Thanks so much for your interest in my blog! I noticed that it was down the other day, but didn’t jump on it right away because I didn’t think anyone was looking at it anymore. It’s nice to know someone else noticed! I confess that I’ve had almost zero time to work on the blog for a long time, and my interests are elsewhere these days.

I will try to take a look at the site and bring it back online this week.

Cheers, Matt

**Comment by 0xFA11** [comment]
Oh, that's great news! 😎🔥🎉

**Comment by matsaleh13** [comment]
The site should be back up now. Sorry for the outage.

FYI I haven’t maintained the site in a long time, and my professional focus is on other topics. I don’t really plan on adding more content, so it’s possible I will decommission the site permanently in a few months. That’s not a certainty, but I’m thinking about it.

If I can find a way to cheaply “park” the existing pages someplace else, I may do that. As it is, it’s costing me about $250USD per year to keep the site up.

Meanwhile, thanks for your interest, and please stay safe and well!

Matt



From: Matthew Walker <matsaleh13@live.com>
Sent: Tuesday, April 14, 2020 9:21 AM
To: MFatihMAR/Game-Networking-Resources <reply@reply.github.com>; MFatihMAR/Game-Networking-Resources <Game-Networking-Resources@noreply.github.com>
Cc: Matthew Walker <matsaleh13@gmail.com>; Mention <mention@noreply.github.com>
Subject: RE: [MFatihMAR/Game-Networking-Resources] gameserverarchitecture.com seems to be down (#28)

Hey Guys,

Thanks so much for your interest in my blog! I noticed that it was down the other day, but didn’t jump on it right away because I didn’t think anyone was looking at it anymore. It’s nice to know someone else noticed! I confess that I’ve had almost zero time to work on the blog for a long time, and my interests are elsewhere these days.

I will try to take a look at the site and bring it back online this week.

Cheers, Matt

**Comment by ondrowan** [comment]
@matsaleh13 You could use [GitHub Pages](https://pages.github.com/) with some static site generator to host it for free. You don't even need to pay for domain that way.

**Comment by matsaleh13** [comment]
That’s not a bad suggestion, thanks. I may look into that.

Cheers.

**Comment by Dahrkael** [comment]
Hello, just passing by to say I did a full backup of the site to web.archive.org, as the previous backup was mostly empty.
Backed up every page one by one, except individual glossary entries (they are shown when hovering anyway) and tags.

**Comment by 0xFA11** [comment]
Hey @Dahrkael,

That's super cool, thanks! :)
